### ISSUE TITLE
Documentation for how to contribute

### ISSUE THREAD

**Issue by mrdeveloperdude** [qbs/qbs.io#1]
I just recently decided to give Qbs a proper go because... I don't want to end up in CMake land ever again.

I have pledged in the comments of [this bugreport](https://bugreports.qt.io/browse/QBS-1715) that I will contribute to the effort of making Qbs in general and Qbs documentation in particular more approachable for "mere mortals".

So far I have come this far:

```
$ git clone git@github.com:mrdeveloperdude/qbs.io.git
# ...

$ cd qbs.io/

$ sudo apt install hugo nodejs npm
# ...

$ npm install
# ...

$ npm audit fix
# ...

$ npx browserslist@latest --update-db
# ...

$ npx browserslist@latest --update-db
# Because one time was not enough apparently


$ hugo server

Start building sites … 
Built in 2031 ms
Error: Error building site: POSTCSS: failed to transform "css/main.css" (text/css): Error: ENOENT: no such file or directory, stat '/home/leo/Desktop/Projects/QbsDoc/qbs.io/stdin'
    at Object.statSync (fs.js:1016:3)
    at trackModified (/home/leo/Desktop/Projects/QbsDoc/qbs.io/node_modules/tailwindcss/lib/lib/setupContextUtils.js:463:46)
    at Object.getContext (/home/leo/Desktop/Projects/QbsDoc/qbs.io/node_modules/tailwindcss/lib/lib/setupContextUtils.js:818:5)
    at /home/leo/Desktop/Projects/QbsDoc/qbs.io/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:142:53
    at /home/leo/Desktop/Projects/QbsDoc/qbs.io/node_modules/tailwindcss/lib/processTailwindFeatures.js:41:11
    at plugins (/home/leo/Desktop/Projects/QbsDoc/qbs.io/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/home/leo/Desktop/Projects/QbsDoc/qbs.io/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/leo/Desktop/Projects/QbsDoc/qbs.io/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/leo/Desktop/Projects/QbsDoc/qbs.io/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/home/leo/Desktop/Projects/QbsDoc/qbs.io/node_modules/postcss/lib/lazy-result.js:206:17) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/leo/Desktop/Projects/QbsDoc/qbs.io/stdin'
}
```
My idea is that I will contribute some documentation as I learn Qbs from a complete beginner's perspective. Hopefully I will manage to capture the relevant questions and present them in a good way as documentation.

But before I can succeed with this, I need to get the damn thing running locally. I have used NPM many years ago and hugo is completely new to me.

There seems to be no README file in this repo, so maybe my first contribution could be such a README file. So what are the steps missing to get this running locally?

Thanks!

**Comment by ckandeler** [comment]
That's not the qbs repo. You want https://github.com/qbs/qbs.

**Comment by mrdeveloperdude** [comment]
> That's not the qbs repo. You want https://github.com/qbs/qbs.

No, I want the Qbs website, that is where documentation lives.

**Comment by ckandeler** [comment]
I don't think you'll have much fun editing the generated HTML. The documentation sources are in the git repo, in the doc/ directory.
